#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/mount/arbeitsdaten/asr/licu/E2E/espnet/tools/python_user_base"
export PATH="/mount/arbeitsdaten/asr/licu/E2E/espnet/tools/python_user_base/bin":${PATH}
export PATH=/mount/arbeitsdaten/asr/licu/E2E/miniconda3/bin:${PATH}
