# network architecture
# encoder related
etype: vggblstmp     # encoder architecture type
elayers: 5
eunits: 1024
eprojs: 1024
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 1024
# attention related
atype: location
adim: 1024
awin: 5
aheads: 4
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.5

# label smoothing
lsm-type: unigram
lsm-weight: 0.05

# minibatch related
batch-size: 20
maxlen-in: 400  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 15
patience: 15

# scheduled sampling option
sampling-probability: 0.0

# Report CER & WER
report-cer: true
report-wer: true
